# Get your lean api token from dev portal (https://dev.leantech.me)
# production
logging.level.org.apache.http: DEBUG
app.token:
  50676d15-e076-4cdf-be11-15f8154324d0

  # Lean API base url
lean.base.host: https://api.leantech.me
  
  # Location of the prod certificates and keys
certificate.name: lean_prod_cert_chain
private.key.name: prod_privatekey.pem
public.key.name: prod_certificate.crt


p12.filename: firepay.p12
p12.password: 12345

spring:
  datasource:
    password: leandphackathon2023
    url: jdbc:postgresql://db.abimrutwiszevauaedho.supabase.co:5432/postgres?user=postgres&password=leandphackathon2023
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    showSql: false
    generateDdl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddlAuto: validate
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
